version: 2
jobs:
  build:
    working_directory: ~/webapp-server
    docker:
    - image: circleci/openjdk:8-jdk-stretch
    
    steps:
    - checkout
    - restore_cache:
        key: webapp-server-{{ checksum "pom.xml" }}
    - run: mvn dependency:go-offline
    - save_cache:
        paths:
        - ~/.m2
        key: webapp-server-{{ checksum "pom.xml" }}
    - run: mvn package
    - store_test_results:
        path: target/surefire-reports
    - store_artifacts:
        path: target/webapp-0.0.1-SNAPSHOT.jar
    - run: 
        name: Install aws and configure
        command: |
          sudo apt-get update && sudo apt-get install python-pip
          sudo pip install awscli
          sudo aws --version
          aws configure set aws_access_key_id ${aws_access_key}
          aws configure set aws_secret_access_key ${aws_secret_key}
          aws configure set region ${aws_region}
          aws configure list
          pwd
          BUILD_COUNTER="${CIRCLE_BUILD_NUM}"
          echo "${BUILD_COUNTER}"
          zip -r ${BUILD_COUNTER}_webapp-server.zip *
          aws s3 cp ${BUILD_COUNTER}_webapp-server.zip s3://${code_deploy_bucket} --region ${aws_region}
          aws deploy create-deployment --application-name csye6225-webapp \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --deployment-group-name csye6225-webapp-server-deployment \
            --ignore-application-stop-failures \
            --s3-location bucket=${code_deploy_bucket},bundleType=zip,key=${BUILD_COUNTER}_webapp-server.zip

  pr_check:
    working_directory: ~/webapp-server
    docker:
    - image: circleci/openjdk:8-jdk-stretch
    steps:
    - checkout
    - restore_cache:
        key: webapp-server-{{ checksum "pom.xml" }}
    - run: mvn dependency:go-offline
    - save_cache:
        paths:
        - ~/.m2
        key: webapp-server-{{ checksum "pom.xml" }}
    - run: mvn package
    - store_test_results:
        path: target/surefire-reports
    - store_artifacts:
        path: target/webapp-0.0.1-SNAPSHOT.jar
    - run: 
        name: Install aws and configure
        command: |
          sudo apt-get update && sudo apt-get install python-pip
          sudo pip install awscli
          sudo aws --version
          aws configure set aws_access_key_id ${aws_access_key}
          aws configure set aws_secret_access_key ${aws_secret_key}
          aws configure set region ${aws_region}
          aws configure list
          pwd
          BUILD_COUNTER="${CIRCLE_BUILD_NUM}"
          echo "${BUILD_COUNTER}"
          zip -r ${BUILD_COUNTER}_webapp-server.zip *
          aws s3 cp ${BUILD_COUNTER}_webapp-server.zip s3://${code_deploy_bucket} --region ${aws_region}
          aws deploy create-deployment --application-name csye6225-webapp \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --deployment-group-name csye6225-webapp-deployment \
            --ignore-application-stop-failures \
            --s3-location bucket=${code_deploy_bucket},bundleType=zip,key=${BUILD_COUNTER}_webapp-server.zip
    environment:
workflows:
  version: 2
  pr-check:
    
    jobs:
    - pr_check
  build_deploy:
    jobs:
    - build:
        filters:  
            branches:
              only:  
                - master