version: 2
orbs:
  aws-s3: circleci/aws-s3@1.0.15
jobs:
  build:
    working_directory: ~/webapp-server
    docker:
    - image: circleci/openjdk:8-jdk-stretch
    
    steps:
    - checkout
    - restore_cache:
        key: webapp-server-{{ checksum "pom.xml" }}
    - run: mvn dependency:go-offline
    - save_cache:
        paths:
        - ~/.m2
        key: webapp-server-{{ checksum "pom.xml" }}
    - run: mvn package
    - store_test_results:
        path: target/surefire-reports
    - store_artifacts:
        path: target/webapp-0.0.1-SNAPSHOT.jar
    - run: 
        name: Install aws and configure
        command: |
          sudo apt-get update && sudo apt-get install python-pip
          sudo pip install awscli
          sudo aws --version

  pr_check:
    working_directory: ~/webapp-server
    docker:
    - image: circleci/openjdk:8-jdk-stretch
    steps:
    - checkout
    - restore_cache:
        key: webapp-server-{{ checksum "pom.xml" }}
    - run: mvn dependency:go-offline
    - save_cache:
        paths:
        - ~/.m2
        key: webapp-server-{{ checksum "pom.xml" }}
    - run: mvn package
    - store_test_results:
        path: target/surefire-reports
    - store_artifacts:
        path: target/webapp-0.0.1-SNAPSHOT.war
    - run: 
        name: Install aws and configure
        command: |
          sudo apt-get update && sudo apt-get install python-pip
          sudo pip install awscli
          sudo aws --version
          aws configure set aws_access_key_id ${aws_access_key}
          aws configure set aws_secret_access_key ${aws_secret_key}
          aws configure set region ${aws_region}
          aws configure list
          pwd
    environment:
workflows:
  version: 2
  pr-check:
    
    jobs:
    - pr_check
  build_deploy:
    jobs:
    - build:
        filters:  
            branches:
              only:  
                - master